### ISSUE TITLE
Erzeugung des Objektes, welches vom VR-Spieler gesteuert wird.

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#20]
Für jeden Spieler ist ein “GameObject” vorgesehen, welches die VR-Steuerung implementiert und alle weiteren Funktionalitäten, die der VR-Spieler benötigt. Dieses muss nach Erstellung des Spiels korrekt erzeugt werden.

**Comment by Glaeric** [comment]
Done
