### ISSUE TITLE
Erzeugung des Objektes, welches vom Tablet-Spieler gesteuert wird.

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#21]
Für jeden Spieler ist ein “GameObject” vorgesehen, welches die Tablet-Steuerung implementiert und alle weiteren Funktionalitäten, die der Tablet-Spieler benötigt. Dieses muss nach Erstellung des Spiels korrekt erzeugt werden.

**Comment by Glaeric** [comment]
Done
