### ISSUE TITLE
Es muss eine Tasche in der VR geben. In dieser werden Gegenstände eingelagert. Beinhaltete Gegenstände sind sowohl in der VR, als auch beim Tablet-Spieler sichtbar

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#22]
Eine wichtige Komponente des Spiels ist der Austausch von Gegenständen.
Dafür ist ein ein Objekt “Tasche” vorgesehen. 
Der gesamte Inhalt dieser Tasche ist sowohl für den VR-Spieler weiterhin sichtbar, genauso aber für den Tablet-Spieler.

**Comment by theNameIsMud** [comment]
Eine einfache Lösung mit RemoteActions ist implementiert.

**Funktionsweise:**
Jede Instanz des Spiels hat ihre lokale Tasche(Liste). Über Commands und RPCCalls werden können auf beiden Instanzen Objekte hinzugefügt und gelöscht werden.

**Problem:**
Die Remote Actions unterstützen nur primitive Datentypen sprich es kann keine Klasse(die das Object beschreibt) versendet werden.

**Lösung:**
1: Es wird aus der Klasse ein Struct welches nur aus primitiven Datentypen besteht generiert. Das Struct wird dann über die RAs verschickt und auf der anderen Seite wird die Klasse wieder erstellt.
2: Es gibt eine Datenbank aus Objekten über das Netzwerk wird nur die ID verschickt und lokal aus der Datenbank das entsprechende Objekt geholt. Nachteil: Die Objekte müssen statisch sein.
3: Eigene Serialization Funktion. Habe aber keine Ahnung davon und vermutl. sehr schwer

**Comment by theNameIsMud** [comment]
Lösung 1 realisiert:
StorageDto Structs werden übertragen über ein Enum kann ausgewählt werden um welchen ItemTyp es sich handelt.
Das Arzttaschen Gameobject muss mit dem NetworkStorage Script ausgestattet werden, der Spieler(das Netzwerk Object, falls unterschiedlich) mit dem NetworkPlayerController.
