### ISSUE TITLE
Der VR-Spieler muss die Möglichkeit haben, ein Item aus der VR dem Tablet-Spieler zu übergeben

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#23]
Eine wichtige Komponente des Spiels ist der Austausch von Gegenständen. 
Der VR-Spieler kann Gegenstände aus seiner Umgebung aufnehmen und soll diese für den Tablet-Spieler verwendbar machen. Dafür muss er den Gegenstand in eine Tasche legen können. Wenn er dies macht, wird der Gegenstand für den Tablet-Spieler sichtbar.
Der gesamte Inhalt dieser Tasche ist sowohl für den VR-Spieler weiterhin sichtbar, genauso aber für den Tablet-Spieler.

**Comment by Glaeric** [comment]
Done
