### ISSUE TITLE
Der Tablet-Spieler muss die Möglichkeit haben, ein Item aus seinem Inventar dem VR-Spieler zu übergeben.

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#24]
Eine wichtige Komponente des Spiels ist der Austausch von Gegenständen.
Der Tablet-Spieler soll Gegenstände aus seinem persönlichen Inventar dem VR-Spieler zugänglich machen können. Dafür braucht er eine Funktion, die eine Verschiebung von Gegenständen von dem Inventar des Tablet-Spielers zum Inventar gemeinsam einsehbaren Inventar ermöglicht. Zusätzlich muss das Item in der VR sichtbar werden. 
Der gesamte Inhalt dieser Tasche ist sowohl für den VR-Spieler weiterhin sichtbar, genauso aber für den Tablet-Spieler.

**Comment by Glaeric** [comment]
Done
