### ISSUE TITLE
Der Tablet-Spieler muss die Möglichkeit haben, ein Item aus dem gemeinsamen Inventar zu nehmen

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#25]
Eine wichtige Komponente des Spiels ist der Austausch von Gegenständen.
 Der Tablet-Spieler soll Gegenstände aus dem gemeinsamen Inventar in sein persönliches Inventar verschieben können.. Dafür braucht er eine Funktion, die eine Verschiebung von Gegenständen von dem gemeinsamen Inventar zum Inventar des Tablet-Spielers ermöglicht. Zusätzlich muss das Item in der VR entfernt/nicht mehr sichtbar gemacht werden.

**Comment by Glaeric** [comment]
Done
