### ISSUE TITLE
Übertragung Statusinformationen Patient

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#26]
Die Statuswerte der an den Patienten angeschlossenen Messgeräte werden nur dem Spieler an dem Tablet angezeigt, ermittelt werden diese aber in der VR. Durch Aktionen an dem Patienten in der VR verändern sich diese Werte.

**Comment by theNameIsMud** [comment]
Der Patient hat 3 Int Werte: seinen Puls, Blutdruck und Sauerstoffsättigung, diese werden mit SyncVars synchronisiert. Über Commands können die Werte geändert werden, der übergebene Wert wird addiert

Der Patient muss mit dem NetworkPlayerHealth Script ausgestattet werden, der Spieler(das Netzwerk Object, falls unterschiedlich) mit dem NetworkPlayerController.
