### ISSUE TITLE
HTC Vive Hardware Integration

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#6]
Der erste Schritt in der Entwicklung der VR-Controls sollte sein, dass die HTC Vive Hardware in das Projekt integriert wird. Die dazugehörigen Unity-Plugins müssen hinzugefügt und evtl. konfiguriert werden.

**Comment by rhodes1337** [comment]
Steam VR und VRTK Plugins sind ins Projekt importiert und funktionieren ordnungsgemäß.
