### ISSUE TITLE
Abdunkeln des Bildschirms

### ISSUE THREAD

**Issue by Bosdan** [Bosdan/epicsave#8]
Eine Sache die bei der Entwicklung von VR-Spielen bedacht werden muss ist, dass Spieler keine Collider haben. Sie können sich in einem Raum frei bewegen und physikalische Objekte in der virtuellen Realität ignorieren. Dadurch ist es dem Spieler möglich durch Wände und andere Objekte hindurch zu schauen.

**Comment by rhodes1337** [comment]
Sobald das HDM einen Collider betritt wird nun der Bildschirm langsam abgedunkelt. Beim verlassen des Collider wird das Bild langsam wieder angezeigt.

**Comment by Lordroran** [comment]
Haben wir am Rand des betretbaren Bereichs den momentan Collider? oder soll der Spieler auch weitergehen können?
